version: "1"

services:
  mongo-container:
    image: mongo
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  back:
    image: node
    container_name: client-registration
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
    depends_on:
      - mongo-container
